export const authStyles = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#F6F4FA",
    fontFamily: "'Outfit', system-ui, sans-serif",
    padding: 16,
  },
  card: {
    width: "100%",
    maxWidth: 380,
    background: "#fff",
    borderRadius: 20,
    padding: 28,
    boxShadow: "0 8px 30px rgba(43,33,64,.08)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  title: {
    fontSize: 22,
    fontWeight: 800,
    color: "#2B2140",
    margin: "0 0 6px",
  },
  label: {
    fontSize: 14,
    fontWeight: 600,
    color: "#2B2140",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  input: {
    border: "1.5px solid #D9D3E8",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 15,
    fontFamily: "inherit",
  },
  button: {
    marginTop: 6,
    background: "#2B2140",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "12px 14px",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
  },
  error: {
    background: "#FCE9EC",
    border: "1px solid #E8467C",
    color: "#B0335A",
    borderRadius: 10,
    padding: "8px 12px",
    fontSize: 13.5,
  },
  success: {
    background: "#E9F7F0",
    border: "1px solid #1E9E6A",
    color: "#166B48",
    borderRadius: 10,
    padding: "8px 12px",
    fontSize: 13.5,
  },
  footer: {
    fontSize: 13.5,
    textAlign: "center",
    marginTop: 4,
    color: "#5B5470",
  },
  link: {
    color: "#5B8DEF",
    fontWeight: 600,
    textDecoration: "none",
  },
};
